# Generated by Django 5.1.9 on 2026-01-28 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurante_mesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(verbose_name='Data e Hora da Reserva')),
                ('cantidad_personas', models.PositiveIntegerField(verbose_name='Número de Comensais')),
                ('codigo_reserva', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Código de Reserva')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Especiais')),
                ('total_reserva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurante_mesa.restaurantemesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_restaurante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de Restaurante',
                'verbose_name_plural': 'Reservas de Restaurante',
                'db_table': 'reserva_restaurante',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
