# Generated by Django 5.1.9 on 2026-01-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRestaurante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(null=True)),
            ],
            options={
                'db_table': 'menu_restaurante',
                'managed': True,
            },
        ),
    ]
