# Generated by Django 5.1.9 on 2026-01-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10, unique=True)),
                ('piso', models.IntegerField(choices=[(1, 'Piso 1'), (2, 'Piso 2'), (3, 'Piso 3'), (4, 'Piso 4'), (5, 'Piso 5'), (6, 'Piso 6'), (7, 'Piso 7'), (8, 'Piso 8')], default=1)),
                ('tipo_ocupacion', models.CharField(choices=[('doble', 'Doble (2 personas)'), ('triple', 'Triple (3 personas)'), ('cuadruple', 'Cuádruple (4 personas)')], default='doble', max_length=20)),
                ('tamaño_cama', models.CharField(choices=[('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin')], default='queen', max_length=20)),
                ('categoria', models.CharField(choices=[('estandar', 'Estándar'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('suite_presidencial', 'Suite Presidencial'), ('estudio', 'Estudio')], default='estandar', max_length=20)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('condicion', models.CharField(choices=[('basica', 'Básica'), ('funcional', 'Funcional'), ('confort', 'Confort'), ('lujo', 'Lujo')], editable=False, max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En Limpieza'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal de la habitación', null=True, upload_to='habitaciones/')),
                ('metros_cuadrados', models.PositiveIntegerField(default=45, help_text='Metros cuadrados de la habitación')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitacion',
                'ordering': ['piso', 'numero_habitacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('url_imagen', models.URLField(blank=True, help_text='URL de imagen externa (opcional)', max_length=500, null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que se mostrará la imagen')),
                ('activa', models.BooleanField(default=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='habitacion.habitacion')),
            ],
            options={
                'verbose_name': 'Imagen de Habitación',
                'verbose_name_plural': 'Imágenes de Habitaciones',
                'db_table': 'imagen_habitacion',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
