# Generated by Django 5.1.9 on 2026-01-28 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon_eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(verbose_name='Fecha y Hora del Evento')),
                ('cantidad_invitados', models.PositiveIntegerField(verbose_name='Número de Invitados')),
                ('codigo_evento', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Código de Evento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total_reserva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='salon_eventos.salonevento', verbose_name='Salón de Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_salon', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva de Salón',
                'verbose_name_plural': 'Reservas de Salones',
                'db_table': 'reserva_salon',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
