# Generated by Django 5.1.9 on 2026-01-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono (ej: gluten, lacteos, etc.)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Alérgeno',
                'verbose_name_plural': 'Alérgenos',
                'db_table': 'alergeno',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('principal', 'Plato Principal'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('aperitivo', 'Aperitivo'), ('ensalada', 'Ensalada'), ('sopa', 'Sopa'), ('guarnicion', 'Guarnición')], default='principal', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ingredientes', models.TextField(blank=True, help_text='Lista de ingredientes separados por comas', null=True)),
                ('tiempo_preparacion', models.PositiveIntegerField(default=15, help_text='Tiempo de preparación en minutos')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del plato', null=True, upload_to='platos/')),
                ('url_imagen', models.URLField(blank=True, help_text='URL de imagen externa (opcional)', max_length=500, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que se mostrará en el menú')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alergenos', models.ManyToManyField(blank=True, related_name='platos', to='plato.alergeno')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': 'plato',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
    ]
