# Generated by Django 5.1.9 on 2026-01-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='salones/', verbose_name='Imagen del salón')),
            ],
            options={
                'db_table': 'salon_eventos',
                'managed': True,
            },
        ),
    ]
