# Generated by Django 5.1.9 on 2026-01-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonevento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado de Disponibilidad'),
        ),
    ]
